// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDut3JHIeyxPjT1lEQwx87kWPiNj0hrOIE',
    appId: '1:198523161337:web:84829f359cd4d42325f028',
    messagingSenderId: '198523161337',
    projectId: 'offset-production-erp',
    authDomain: 'offset-production-erp.firebaseapp.com',
    storageBucket: 'offset-production-erp.firebasestorage.app',
    measurementId: 'G-FG1VS7T8KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCXbJ4nQD6yHg2EVtFtlPuMB02VLAYsiM',
    appId: '1:198523161337:android:fa6b5ca5fe2f8a9625f028',
    messagingSenderId: '198523161337',
    projectId: 'offset-production-erp',
    storageBucket: 'offset-production-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYQu28cPdbRqwM7mu-sgfn_2hgyjiBoA4',
    appId: '1:198523161337:ios:eeb33414b877f56825f028',
    messagingSenderId: '198523161337',
    projectId: 'offset-production-erp',
    storageBucket: 'offset-production-erp.firebasestorage.app',
    iosBundleId: 'com.example.offsetProductionErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYQu28cPdbRqwM7mu-sgfn_2hgyjiBoA4',
    appId: '1:198523161337:ios:eeb33414b877f56825f028',
    messagingSenderId: '198523161337',
    projectId: 'offset-production-erp',
    storageBucket: 'offset-production-erp.firebasestorage.app',
    iosBundleId: 'com.example.offsetProductionErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDut3JHIeyxPjT1lEQwx87kWPiNj0hrOIE',
    appId: '1:198523161337:web:ce9c1336b5940fa425f028',
    messagingSenderId: '198523161337',
    projectId: 'offset-production-erp',
    authDomain: 'offset-production-erp.firebaseapp.com',
    storageBucket: 'offset-production-erp.firebasestorage.app',
    measurementId: 'G-8C2WM0X1TY',
  );
}
